### ISSUE TITLE
node.Value() doesn't recurse

### ISSUE THREAD

**Issue by cburgmer** [spyzhov/ajson#16]
When looking up `$.a` on `{"a": {"b":42}}` and using `node.Value()` to derive the value, I receive `{"b":{}}` instead of the expected `{"b":42}`.
Am I doing it right?

**Comment by spyzhov** [comment]
Thanks, will fix it asap.

**Comment by spyzhov** [comment]
@cburgmer , I check it once again, and found, that it's not a bug. 
method `node.Value()` do not parse value recursive and that is written on [documentation](https://pkg.go.dev/github.com/spyzhov/ajson?tab=doc#Node.Value)
```
It returns []*Node, if current node type is Array.
It returns map[string]*Node, if current node type is Object.
BUT! Current method doesn't calculate underlying nodes (use method Node.Unpack for that).
```
If you want to get "clear" value, please use [`node.Unpack()`](https://pkg.go.dev/github.com/spyzhov/ajson?tab=doc#Node.Unpack)

I apologize for the misunderstanding.
