### ISSUE TITLE
Are current 0.x versions stable?

### ISSUE THREAD

**Issue by anshul-jain881** [spyzhov/ajson#29]
I'm interested in using this library but I don't see a 1.x version. Are these 0.x versions stable? When do you plan to release 1.0?

**Comment by spyzhov** [comment]
Hello! Yes, it's stable enough. I fix bugs as soon as I find it. You can use it for most usual requests.
Version 1.x - planned to the end of this year, but interfaces will be different from current (more useful).

I use current version of package at least in 3 my pet-projects and 2 business-projects.
