### ISSUE TITLE
Treeview

### ISSUE THREAD

**Issue by DiskGetor** [spyzhov/ajson#34]
How to use this lib for creat treeview with fyne gui

**Comment by spyzhov** [comment]
Hi! Sure, but I don't know for what reason? 

This library is useful when you have a big structure and you don't like to unmarshal it all, but you need to change some part of it and pass it further. Or when your data can be changed and you don't know the structure for sure.

I created a small example with the `Treeview`:
```go
package main

import (
	"io"
	"net/http"
	"sort"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"
	"fyne.io/fyne/v2/theme"
	"fyne.io/fyne/v2/widget"

	"github.com/spyzhov/ajson"
	"github.com/spyzhov/safe"
)

const source = "https://raw.githubusercontent.com/matthlavacka/car-list/master/car-list.json"

func main() {
	a := app.NewWithID("io.fyne.treeview.demo")
	a.SetIcon(theme.FyneLogo())
	w := a.NewWindow("Treeview Demo")

	w.SetMaster()
	w.SetContent(makeTreeTab(w))
	w.Resize(fyne.NewSize(640, 460))
	w.ShowAndRun()
}

func makeTreeTab(_ fyne.Window) fyne.CanvasObject {
	res := safe.Must(http.Get(source)).(*http.Response)
	defer safe.Close(res.Body, "response from GET "+source)
	buf := safe.Must(io.ReadAll(res.Body)).([]byte)
	root := ajson.Must(ajson.Unmarshal(buf))
	data := map[string][]string{"": {}}

	nodes := safe.Must(root.JSONPath("$..[?(@.brand && @.models)]")).([]*ajson.Node)
	for _, node := range nodes {
		brand := node.MustKey("brand").MustString()
		models := node.MustKey("models").MustArray()
		data[""] = append(data[""], brand)
		data[brand] = make([]string, len(models))
		for i, model := range models {
			data[brand][i] = model.MustString()
		}
	}

	sort.Strings(data[""])
	return widget.NewTreeWithStrings(data)
}

```

**Comment by DiskGetor** [comment]
> Hi! Sure, but I don't know for what reason?
> 
> This library is useful when you have a big structure and you don't like to unmarshal it all, but you need to change some part of it and pass it further. Or when your data can be changed and you don't know the structure for sure.
> 
> I created a small example with the `Treeview`:
> 
> ```go
> package main
> 
> import (
> 	"io"
> 	"net/http"
> 	"sort"
> 
> 	"fyne.io/fyne/v2"
> 	"fyne.io/fyne/v2/app"
> 	"fyne.io/fyne/v2/theme"
> 	"fyne.io/fyne/v2/widget"
> 
> 	"github.com/spyzhov/ajson"
> 	"github.com/spyzhov/safe"
> )
> 
> const source = "https://raw.githubusercontent.com/matthlavacka/car-list/master/car-list.json"
> 
> func main() {
> 	a := app.NewWithID("io.fyne.treeview.demo")
> 	a.SetIcon(theme.FyneLogo())
> 	w := a.NewWindow("Treeview Demo")
> 
> 	w.SetMaster()
> 	w.SetContent(makeTreeTab(w))
> 	w.Resize(fyne.NewSize(640, 460))
> 	w.ShowAndRun()
> }
> 
> func makeTreeTab(_ fyne.Window) fyne.CanvasObject {
> 	res := safe.Must(http.Get(source)).(*http.Response)
> 	defer safe.Close(res.Body, "response from GET "+source)
> 	buf := safe.Must(io.ReadAll(res.Body)).([]byte)
> 	root := ajson.Must(ajson.Unmarshal(buf))
> 	data := map[string][]string{"": {}}
> 
> 	nodes := safe.Must(root.JSONPath("$..[?(@.brand && @.models)]")).([]*ajson.Node)
> 	for _, node := range nodes {
> 		brand := node.MustKey("brand").MustString()
> 		models := node.MustKey("models").MustArray()
> 		data[""] = append(data[""], brand)
> 		data[brand] = make([]string, len(models))
> 		for i, model := range models {
> 			data[brand][i] = model.MustString()
> 		}
> 	}
> 
> 	sort.Strings(data[""])
> 	return widget.NewTreeWithStrings(data)
> }
> ```

I am sorry, i still can not change  regexp  for this json,please help me again. i want to write  a tool for decode protobuf .

{
  "group<1>": {
    "binary<1>": "game/system/session/info",
    "packed<2>": {
      "group<2>": [
        {
          "varint<1>": 0,
          "binary<2>": "d3048a459417e6c0b7d39c971b99a58029f2720f7b2a70c992c826ce48184069",
          "binary<3>": "6593D03B-92BC-4BC6-BF54-D16BB0271AF9",
          "binary<4>": "Apple-iPhone10,3"
        },
        {
          "varint<1>": 1,
          "binary<2>": "",
          "binary<3>": "EAAIe5YPC68wBAPGE5l7JEtIE9BfPQmbcpQ92b0c9fD29vKn5ZCwHkutEjpX2PEcvyBLDqo15gNi1x0VN7U6d26QDaABEDaVzu3vuZBYKtvHH130O9Kna4742s6B8dtr1aKJUw7HuuyNWObpWYZCqBDGvypB7Js93oBISkwWrjbuYZAooY5vHLHFPyuIcLAcV8ZAX9sRFn3un18KZA0MEuDtgekU4ZBTJ1doEQmQ4DCLXwZDZD"
        }
      ],
      "binary<3>": "6593D03B-92BC-4BC6-BF54-D16BB0271AF9"
    },
    "varint<3>": 0,
    "binary<4>": "",
    "varint<5>": 0
  }
}

**Comment by spyzhov** [comment]
Sorry, but I can't understand, what you'd like to do? Could you please explain the task?

**Comment by DiskGetor** [comment]
> Sorry, but I can't understand, what you'd like to do? Could you please explain the task?

Sorry my bad English, my teacher. I want to write a tool for decode protobuf raw but. And to chang regexp for this api 
nodes := safe.Must(root.JSONPath("$..[?(@.brand && @.models)]")).([]*ajson.Node

Use this tool for check protobuf,tdf or another protocol stream buffer decode or encode wright or wrong. This is  demo picture,but i can not load json on tree, and the demo codes has some of bug.

![Screenshot_20210521_081742_com realvnc viewer android](https://user-images.githubusercontent.com/19886504/119064519-18019f00-ba0e-11eb-925a-c4f5cbbf7ae4.jpg)
