### ISSUE TITLE
length of a filtered list

### ISSUE THREAD

**Issue by prashanth-hegde** [spyzhov/ajson#39]
I just discovered this project a few hours ago, and very impressed by this. I've been playing with `ajson` and discovered (or not discovered) a way to print the length of a filtered list. For example: 

The following command outputs a list, but if I want to print out the number of results returned, I found I cannot use the `.length` operator there. Am I missing something here or is it that feature is missing? 

```sh 
ajson '$.results[?(@.gender=="female")]' "https://randomuser.me/api/?results=10"
```

Looking to achieve a result like this
```sh
./ajson '$.results[?(@.gender=="female")]' "https://randomuser.me/api/?results=10" | jq 'length'
```

**Comment by spyzhov** [comment]
Hi! Thanks for the kind words! :-)
You can use any valid JSONPath or `eval` string. So your example could be solved like this:
```
ajson 'length($.results[?(@.gender=="female")])' "https://randomuser.me/api/?results=10"
```
