### ISSUE TITLE
M1 build

### ISSUE THREAD

**Issue by imarsman** [spyzhov/ajson#51]
This is not for myself, as I have Go installed, but not all of my coworkers do. I have used ajson to validate the contents of a json file for work and coworkers will require an M1 build. I can provide that for them if needed but if you can add it to your build set I would be grateful. I very much enjoy using the cli tool and look forward to using the library as well. Thank-you.

**Comment by spyzhov** [comment]
Hey! I added an `arm64` version in the last release: https://github.com/spyzhov/ajson/releases/download/v0.7.1/ajson_darwin_arm64.zip

**Comment by imarsman** [comment]
Thank-you very much!
