### ISSUE TITLE
Eval `length()` function returns wrong answer after filtering array

### ISSUE THREAD

**Issue by Joey29-1** [spyzhov/ajson#67]
The `length()` function in `Eval()` does not return the correct answer if the array of objects is filtered.

In the code snippet below, there is no element in `$.items` that matches the array filtering condition, but the length of the resulting array is still evaluated to 1 instead of 0.

```
json := []byte(`
{
  "items": [
    {
      "price":1, 
      "type": "A"
    }, 
    {
      "price":2, 
      "type": "B"
    }, 
    {
      "price":3, 
      "type": "C"
    }
  ]
}`)

root, err := ajson.Unmarshal(json)
if err != nil {
  panic(err)
}
res1, err := ajson.Eval(root, `length($.items[?(@.type == "D")])`)
if err != nil {
  panic(err)
}
fmt.Printf("Result: %+v", res1.MustNumeric()) // Expected: 0, Actual: 1

res2, err := ajson.Eval(root, `length($.items[?(@.type == "A")])`)
if err != nil {
  panic(err)
}
fmt.Printf("Result: %+v", res2.MustNumeric()) // Expected: 1, Actual: 2

res3, err := ajson.Eval(root, `length($.items[?(@.type == "A" || @.type == "B")])`)
if err != nil {
  panic(err)
}
fmt.Printf("Result: %+v", res3.MustNumeric()) // Expected: 2, Actual: 2
```

**Comment by Joey29-1** [comment]
What I have figured out after tracing the code:

- If none of the elements match the array filter condition, the resultant Node has NodeType `Null`. According to the implementation of the `length()` function, a value of `1` is returned.
- On a similar vein, if only 1 element matches the filter condition, the resultant Node has NodeType `Object` (I thought it was `Array`). The `length()` function then returns `node.Size()`.

**Comment by spyzhov** [comment]
Thank you for sharing this! I will try to prepare the fix today ASAP.

**Comment by spyzhov** [comment]
Fixed in [v0.9.2](https://github.com/spyzhov/ajson/releases/tag/v0.9.2)

**Comment by tpoxa** [comment]
BTW why the length of null is 1? @spyzhov  
How can I check if an array has elements while array itself could be null?

**Comment by spyzhov** [comment]
Good point... length of the element is equal to 1, for the reason that the value that you select is always the array, as soon as any JSONPath response is array.

What you are asking about... I suppose I should add some new functions, like `is_*type*`. I will try to add it asap, or feel free to suggest changes :-)

**Comment by tpoxa** [comment]
thanks @spyzhov
