### ISSUE TITLE
Why don't you provide the functionality to update the data inside the node?

### ISSUE THREAD

**Issue by liushiqi1001** [spyzhov/ajson#77]
I think your project is great, but why don't you have a function to update the data inside the nodes? Is there any other consideration behind that?

**Comment by liushiqi1001** [comment]
I've been searching for a while but couldn't find it. If project support updating the data inside the nodes, how should I use that functionality?

**Comment by spyzhov** [comment]
Sorry, I missed this request. Yes, you can use `Set` function to modify data inside nodes: https://pkg.go.dev/github.com/spyzhov/ajson#Node.Set
